<a href="https://colab.research.google.com/github/lsw1121/BEAT-3-/blob/main/3%EC%9E%A5_%EC%85%80%ED%94%84_%EC%96%B4%ED%85%90%EC%85%98_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 코드 3-1 변수 정의
- 입력 벡터 시퀀스 X와 쿼리, 키, 밸류 구축에 필요한 행렬들을 정의했습니다.

In [1]:
import torch
x = torch.tensor([
    [1.0, 0.0, 1.0, 0.0],
    [0.0, 2.0, 0.0, 2.0],
    [1.0, 1.0, 1.0, 1.0],
])
w_query = torch.tensor([
        [1.0, 0.0, 1.0],
        [1.0, 0.0, 0.0],
        [0.0, 0.0, 1.0],
        [0.0, 1.0, 1.0]
])
w_key = torch.tensor([
        [0.0, 0.0, 1.0],
        [1.0, 1.0, 0.0],
        [0.0, 1.0, 0.0],
        [1.0, 1.0, 0.0]              
])
w_value = torch.tensor([
        [0.0, 2.0, 0.0],
        [0.0, 3.0, 0.0],
        [1.0, 0.0, 3.0],
        [1.0, 1.0, 0.0]              
])

# 코드 3-2 쿼리, 키, 밸류 만들기
- 입력 벡터 시퀀스 X로 쿼리,키, 밸류 벡터들을 만드는 부분입니다.

- 여기서, torch.matmul는 행렬곱을 수행하는 함수입니다.


In [2]:
keys = torch.matmul(x, w_key)
querys = torch.matmul(x, w_query)
values = torch.matmul(x, w_value)

# 코드 3-3 어텐션 스코어 만들기
- 쿼리 벡터들과 키 벡터들을 행렬곱해서 어텐션스코어를 만드는 과정입니다.

- 여기서, keys.T는 키 벡터들을 전치한 행렬입니다.

In [3]:
attn_scores = torch.matmul(querys, keys.T)
attn_scores

tensor([[ 2.,  4.,  4.],
        [ 4., 16., 12.],
        [ 4., 12., 10.]])

# 코드 3-4 소프트맥스 확률값 만들기
- 앞 코드 결과에 키 벡터의 차원 수 제곱근으로 나눈 후 소프트맥스를 취하는 과정입니다.

In [5]:
import numpy as np
from torch.nn.functional import softmax
key_dim_sqrt = np.sqrt(keys.shape[-1])
attn_probs = softmax(attn_scores / key_dim_sqrt, dim=-1)
attn_probs

tensor([[1.3613e-01, 4.3194e-01, 4.3194e-01],
        [8.9045e-04, 9.0884e-01, 9.0267e-02],
        [7.4449e-03, 7.5471e-01, 2.3785e-01]])

# 코드 3-5 소프트맥스 확률과 밸류를 가중합하기
- 앞 코드에서 구한 소프트맥스 확률과 밸류 벡터들을 가중합하는 과정입니다.

In [6]:
weighted_values = torch.matmul(attn_probs, values)
weighted_values

tensor([[1.8639, 6.3194, 1.7042],
        [1.9991, 7.8141, 0.2735],
        [1.9926, 7.4796, 0.7359]])