<a href="https://colab.research.google.com/github/lsw1121/BEAT-3-/blob/main/%ED%94%BC%EB%93%9C%ED%8F%AC%EC%9B%8C%EB%93%9C_%EB%89%B4%EB%9F%B4_%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC%EC%99%80_%EB%A0%88%EC%9D%B4%EC%96%B4_%EC%A0%95%EA%B7%9C%ED%99%94_%EC%98%88%EC%8B%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 코드 3-6 피드포워드 뉴럴 네트워크 계산 예시 (1)
- 여기서, x는 입력이고 w1은 입력층-은닉층을 연결하는 가중치, b1은 입력층-은닉층을 연결하는 바이어스입니다.

    그리고 w2는 은닉층-출력층을 연결하는 가중치, b2는 은닉층-출력층을 연결하는 바이어스입니다.

In [2]:
import torch
x = torch.tensor([2, 1])
w1 = torch.tensor([[3, 2, -4],[2, -3, 1]])
b1 = 1
w2 = torch.tensor([[-1, 1],[1, 2], [3, 1]])
b2 = -1

# 코드 3-7 피드포워드 뉴럴 네트워크 계산 예시(2)
- h_preact는 입력 x와 w1를 행렬곱한 뒤 b1을 더한 것입니다. 
- 그 다음으로 ReLU를 취해 은닉층 h를 만듭니다. 
- 마지막으로 h와 w2를 행렬곱한 뒤 b2를 더해 출력층 y를 계산합니다.

In [7]:
h_preact = torch.matmul(x, w1) + b1
h = torch.nn.functional.relu(h_preact)
y= torch.matmul(h, w2) + b2



In [8]:
h_preact

tensor([ 9,  2, -6])

In [9]:
h

tensor([9, 2, 0])

In [10]:
y

tensor([-8, 12])