<a href="https://colab.research.google.com/github/lsw1121/BEAT-3-/blob/main/%ED%94%BC%EB%93%9C%ED%8F%AC%EC%9B%8C%EB%93%9C_%EB%89%B4%EB%9F%B4_%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 코드 3-6 피드포워드 뉴럴 네트워크 계산 예시 (1)
- 여기서, x는 입력이고 w1은 입력층-은닉층을 연결하는 가중치, b1은 입력층-은닉층을 연결하는 바이어스입니다.

    그리고 w2는 은닉층-출력층을 연결하는 가중치, b2는 은닉층-출력층을 연결하는 바이어스입니다.

In [2]:
import torch
x = torch.tensor([2, 1])
w1 = torch.tensor([[3, 2, -4],[2, -3, 1]])
b1 = 1
w2 = torch.tensor([[-1, 1],[1, 2], [3, 1]])
b2 = -1

# 코드 3-7 피드포워드 뉴럴 네트워크 계산 예시(2)
- h_preact는 입력 x와 w1를 행렬곱한 뒤 b1을 더한 것입니다. 
- 그 다음으로 ReLU를 취해 은닉층 h를 만듭니다. 
- 마지막으로 h와 w2를 행렬곱한 뒤 b2를 더해 출력층 y를 계산합니다.

In [7]:
h_preact = torch.matmul(x, w1) + b1
h = torch.nn.functional.relu(h_preact)
y= torch.matmul(h, w2) + b2



In [8]:
h_preact

tensor([ 9,  2, -6])

In [9]:
h

tensor([9, 2, 0])

In [10]:
y

tensor([-8, 12])

# 코드 3-8 레이어 정규화 예시
- 다음 코드는 파이토치로 레이어 정규화를 수행하는 역할을 합니다.
- 입력의 모양은 배치 크기(2) * 피처의 차원 수(3)이 됩니다.
- 여기서, torch.nn.LayerNorm(input.shape[-1])이라는 코드는 위 그림에서 화살표 방향대로 레이어 정규화를 수행한다는 의미입니다.

In [11]:
import torch
input = torch.tensor([[1.0, 2.0, 3.0], [1.0, 1.0, 1.0]])
m = torch.nn.LayerNorm(input.shape[-1])
output = m(input)

In [12]:
output

tensor([[-1.2247,  0.0000,  1.2247],
        [ 0.0000,  0.0000,  0.0000]], grad_fn=<NativeLayerNormBackward0>)

- 파이토치의 LayerNorm 객체는 r과 β의 값을 각각 1과 0으로 초기화합니다. 
- 학습 초기 레이어 정규화 수행은 배치 인스턴스의 평균을 빼고 표준편차로 나눈 결과에 1을 곱한 후 0을 더합니다. 
- 이후 학습 과정에서는 태스크를 가장 잘 수행하는 방향으로 이 값들을 업데이트 하는 방식입니다.

In [13]:
m.weight # m.weight은 r 입니다.

Parameter containing:
tensor([1., 1., 1.], requires_grad=True)

In [14]:
m.bias # m.bias는 β입니다.

Parameter containing:
tensor([0., 0., 0.], requires_grad=True)